extends: default

rules:
  comments:
    min-spaces-from-content: 1
  document-start: disable
  indentation:
    spaces: 2
  line-length: disable
  quoted-strings:
    required: only-when-needed
  truthy:
    check-keys: false
